---
- hosts: all
  roles:
    - common
    - docker
    - dnsmasq
    - consul
    - registrator

- include: playbooks/consul-join-wan.yml

- hosts: dc1:&zookeeper_servers
  gather_facts: no
  roles:
    - zookeeper

- hosts: dc1:&mesos_leaders
  gather_facts: no
  roles:
    - mesos

- hosts: dc1:&mesos_followers
  gather_facts: no
  roles:
    - mesos

- hosts: dc1:&marathon_servers
  gather_facts: no
  serial: 1
  roles:
    - marathon

- hosts: dc2:&zookeeper_servers
  gather_facts: no
  roles:
    - zookeeper

- hosts: dc2:&mesos_leaders
  gather_facts: no
  roles:
    - mesos

- hosts: dc2:&mesos_followers
  gather_facts: no
  roles:
    - mesos

- hosts: dc2:&marathon_servers
  gather_facts: no
  serial: 1
  roles:
    - marathon
