---
- hosts: all
  roles:
    - common
    - consul-template
    - docker
    - dnsmasq
    - nginx
    - consul
    - registrator
    - vault
    - zookeeper
    - mesos
    - marathon
    - logging
