---
logstash_image: loshkovskyi/docker-logstash
logstash_image_tag: latest
logstash_ports: "-p 5514:5514 -p 25826:25826/udp"
logstash_service: logstash
logstash_container_name: "{{ logstash_service }}"
logstash_conf_host: /etc/logstash/conf.d
logstash_conf_container: /opt/logstash/conf.d
docker_log_dir: /var/lib/docker/containers
mesos_log_dir: /var/log/mesos
logstash_docker_logs: /docker_logs
logstash_mesos_logs: /mesos_logs
logstash_entrypoint_command: logstash

# Logstash configuration
logstash_input_docker: yes
logstash_input_mesos: yes
logstash_input_syslog: yes
logstash_input_collectd: yes
logstash_output_stdout: yes
logstash_output_logentries: no
logstash_logentries_token: no
